In [1]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\hp\anaconda3\lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sys

print(sys.executable)
print(sys.version)

import mysql.connector
import pandas as pd

c:\Users\HP\anaconda3\python.exe
3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]

In [3]:
conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="Phoenix@261997",
    database="world_tech_layoff"
)

In [5]:
query = """
SELECT *
FROM layoff_staging;
"""

selected_data = pd.read_sql(query, conn)
selected_data


#print(selected_data.head())

#conn.close()

C:\Users\HP\AppData\Local\Temp\ipykernel_20044\1005406861.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  selected_data = pd.read_sql(query, conn)

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Kyte,SF Bay Area,,8/15/2025,100%,Transportation,https://techcrunch.com/2025/08/15/kyte-which-b...,Unknown,$548,United States,8/18/2025
1,Restaurant365,Los Angeles,100.0,8/14/2025,9%,Food,https://www.restaurantbusinessonline.com/techn...,Series C,$127,United States,8/18/2025
2,Oracle,SF Bay Area,188.0,8/13/2025,,Other,https://www.sfchronicle.com/tech/article/oracl...,Post-IPO,,United States,8/18/2025
3,Oracle,Seattle,161.0,8/13/2025,,Other,https://www.geekwire.com/2025/oracle-lays-off-...,Post-IPO,,United States,8/18/2025
4,F5,Seattle,106.0,8/13/2025,2%,Security,https://www.geekwire.com/2024/f5-confirms-new-...,Post-IPO,,United States,8/18/2025
...,...,...,...,...,...,...,...,...,...,...,...
4130,Service,Los Angeles,,3/16/2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,8/31/2020
4131,HopSkipDrive,Los Angeles,8.0,3/13/2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,4/3/2020
4132,Panda Squad,SF Bay Area,6.0,3/13/2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,4/17/2020
4133,Tamara Mellon,Los Angeles,20.0,3/12/2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,3/31/2020
4134,EasyPost,Salt Lake City,75.0,3/11/2020,,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,3/31/2020

In [9]:
# Obtaining the cleaned dataset
query = """
SELECT *
FROM layoff_staging2;
"""

selected_data = pd.read_sql(query, conn)

selected_data.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_20044\2858209909.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  selected_data = pd.read_sql(query, conn)

,country,CITY,company,total_laid_off,date,Year,Month,day,percentage_laid_off,industry,stage,Fundsraised2
0,Finland,Helsinki,F-Secure,70,2023-10-25,2023,10,25,,Security,Post-IPO,0
1,United States,SF Bay Area,Included Health,0,2022-07-25,2022,7,25,6%,Healthcare,Series E,272
2,Ireland,Dublin,&Open,9,2022-11-17,2022,11,17,9%,Marketing,Series A,35
3,Canada,Toronto,#Paid,19,2023-01-27,2023,1,27,17%,Marketing,Series B,21
4,United States,Los Angeles,100 Thieves,12,2022-07-13,2022,7,13,,Consumer,Series C,120

In [8]:
print(f"Rows: {selected_data.shape[0]}")
print(f"Columns: {selected_data.shape[1]}")

Rows: 3454
Columns: 12

In [10]:
selected_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3454 entries, 0 to 3453
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              3454 non-null   object
 1   CITY                 3454 non-null   object
 2   company              3454 non-null   object
 3   total_laid_off       3454 non-null   int64
 4   date                 3454 non-null   object
 5   Year                 3454 non-null   int64
 6   Month                3454 non-null   int64
 7   day                  3454 non-null   int64
 8   percentage_laid_off  3454 non-null   object
 9   industry             3454 non-null   object
 10  stage                3454 non-null   object
 11  Fundsraised2         3454 non-null   int64
dtypes: int64(5), object(7)
memory usage: 323.9+ KB